// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sniffer.proto

package sniffer_prot;

public final class prot_buf {
  private prot_buf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code QueryType}
   */
  public enum QueryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_REQUEST = 0;</code>
     */
    STATUS_REQUEST(0, 0),
    /**
     * <code>DATA_REQUEST = 1;</code>
     */
    DATA_REQUEST(1, 1),
    ;

    /**
     * <code>STATUS_REQUEST = 0;</code>
     */
    public static final int STATUS_REQUEST_VALUE = 0;
    /**
     * <code>DATA_REQUEST = 1;</code>
     */
    public static final int DATA_REQUEST_VALUE = 1;


    public final int getNumber() { return value; }

    public static QueryType valueOf(int value) {
      switch (value) {
        case 0: return STATUS_REQUEST;
        case 1: return DATA_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<QueryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<QueryType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QueryType>() {
            public QueryType findValueByNumber(int number) {
              return QueryType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sniffer_prot.prot_buf.getDescriptor().getEnumTypes().get(0);
    }

    private static final QueryType[] VALUES = values();

    public static QueryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private QueryType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:QueryType)
  }

  /**
   * Protobuf enum {@code ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA = 0;</code>
     */
    DATA(0, 0),
    /**
     * <code>STATUS = 1;</code>
     */
    STATUS(1, 1),
    ;

    /**
     * <code>DATA = 0;</code>
     */
    public static final int DATA_VALUE = 0;
    /**
     * <code>STATUS = 1;</code>
     */
    public static final int STATUS_VALUE = 1;


    public final int getNumber() { return value; }

    public static ResponseType valueOf(int value) {
      switch (value) {
        case 0: return DATA;
        case 1: return STATUS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sniffer_prot.prot_buf.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResponseType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResponseType)
  }

  /**
   * Protobuf enum {@code SnifferStatus}
   */
  public enum SnifferStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SNIFFING_STOPED = 0;</code>
     */
    SNIFFING_STOPED(0, 0),
    /**
     * <code>SNIFFING_RUN = 1;</code>
     */
    SNIFFING_RUN(1, 1),
    ;

    /**
     * <code>SNIFFING_STOPED = 0;</code>
     */
    public static final int SNIFFING_STOPED_VALUE = 0;
    /**
     * <code>SNIFFING_RUN = 1;</code>
     */
    public static final int SNIFFING_RUN_VALUE = 1;


    public final int getNumber() { return value; }

    public static SnifferStatus valueOf(int value) {
      switch (value) {
        case 0: return SNIFFING_STOPED;
        case 1: return SNIFFING_RUN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SnifferStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SnifferStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SnifferStatus>() {
            public SnifferStatus findValueByNumber(int number) {
              return SnifferStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sniffer_prot.prot_buf.getDescriptor().getEnumTypes().get(2);
    }

    private static final SnifferStatus[] VALUES = values();

    public static SnifferStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SnifferStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SnifferStatus)
  }

  public interface SnifferQueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .QueryType type = 1 [default = DATA_REQUEST];
    /**
     * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
     */
    boolean hasType();
    /**
     * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
     */
    sniffer_prot.prot_buf.QueryType getType();

    // optional int32 record_id = 2;
    /**
     * <code>optional int32 record_id = 2;</code>
     */
    boolean hasRecordId();
    /**
     * <code>optional int32 record_id = 2;</code>
     */
    int getRecordId();
  }
  /**
   * Protobuf type {@code SnifferQuery}
   */
  public static final class SnifferQuery extends
      com.google.protobuf.GeneratedMessage
      implements SnifferQueryOrBuilder {
    // Use SnifferQuery.newBuilder() to construct.
    private SnifferQuery(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SnifferQuery(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SnifferQuery defaultInstance;
    public static SnifferQuery getDefaultInstance() {
      return defaultInstance;
    }

    public SnifferQuery getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SnifferQuery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sniffer_prot.prot_buf.QueryType value = sniffer_prot.prot_buf.QueryType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              recordId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sniffer_prot.prot_buf.internal_static_SnifferQuery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sniffer_prot.prot_buf.internal_static_SnifferQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sniffer_prot.prot_buf.SnifferQuery.class, sniffer_prot.prot_buf.SnifferQuery.Builder.class);
    }

    public static com.google.protobuf.Parser<SnifferQuery> PARSER =
        new com.google.protobuf.AbstractParser<SnifferQuery>() {
      public SnifferQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnifferQuery(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SnifferQuery> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .QueryType type = 1 [default = DATA_REQUEST];
    public static final int TYPE_FIELD_NUMBER = 1;
    private sniffer_prot.prot_buf.QueryType type_;
    /**
     * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
     */
    public sniffer_prot.prot_buf.QueryType getType() {
      return type_;
    }

    // optional int32 record_id = 2;
    public static final int RECORD_ID_FIELD_NUMBER = 2;
    private int recordId_;
    /**
     * <code>optional int32 record_id = 2;</code>
     */
    public boolean hasRecordId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 record_id = 2;</code>
     */
    public int getRecordId() {
      return recordId_;
    }

    private void initFields() {
      type_ = sniffer_prot.prot_buf.QueryType.DATA_REQUEST;
      recordId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, recordId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, recordId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sniffer_prot.prot_buf.SnifferQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sniffer_prot.prot_buf.SnifferQuery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SnifferQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sniffer_prot.prot_buf.SnifferQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sniffer_prot.prot_buf.internal_static_SnifferQuery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sniffer_prot.prot_buf.internal_static_SnifferQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sniffer_prot.prot_buf.SnifferQuery.class, sniffer_prot.prot_buf.SnifferQuery.Builder.class);
      }

      // Construct using sniffer_prot.prot_buf.SnifferQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = sniffer_prot.prot_buf.QueryType.DATA_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        recordId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sniffer_prot.prot_buf.internal_static_SnifferQuery_descriptor;
      }

      public sniffer_prot.prot_buf.SnifferQuery getDefaultInstanceForType() {
        return sniffer_prot.prot_buf.SnifferQuery.getDefaultInstance();
      }

      public sniffer_prot.prot_buf.SnifferQuery build() {
        sniffer_prot.prot_buf.SnifferQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sniffer_prot.prot_buf.SnifferQuery buildPartial() {
        sniffer_prot.prot_buf.SnifferQuery result = new sniffer_prot.prot_buf.SnifferQuery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.recordId_ = recordId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sniffer_prot.prot_buf.SnifferQuery) {
          return mergeFrom((sniffer_prot.prot_buf.SnifferQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sniffer_prot.prot_buf.SnifferQuery other) {
        if (other == sniffer_prot.prot_buf.SnifferQuery.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRecordId()) {
          setRecordId(other.getRecordId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sniffer_prot.prot_buf.SnifferQuery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sniffer_prot.prot_buf.SnifferQuery) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .QueryType type = 1 [default = DATA_REQUEST];
      private sniffer_prot.prot_buf.QueryType type_ = sniffer_prot.prot_buf.QueryType.DATA_REQUEST;
      /**
       * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
       */
      public sniffer_prot.prot_buf.QueryType getType() {
        return type_;
      }
      /**
       * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
       */
      public Builder setType(sniffer_prot.prot_buf.QueryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .QueryType type = 1 [default = DATA_REQUEST];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = sniffer_prot.prot_buf.QueryType.DATA_REQUEST;
        onChanged();
        return this;
      }

      // optional int32 record_id = 2;
      private int recordId_ ;
      /**
       * <code>optional int32 record_id = 2;</code>
       */
      public boolean hasRecordId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 record_id = 2;</code>
       */
      public int getRecordId() {
        return recordId_;
      }
      /**
       * <code>optional int32 record_id = 2;</code>
       */
      public Builder setRecordId(int value) {
        bitField0_ |= 0x00000002;
        recordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 record_id = 2;</code>
       */
      public Builder clearRecordId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        recordId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SnifferQuery)
    }

    static {
      defaultInstance = new SnifferQuery(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SnifferQuery)
  }

  public interface SnifferResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .ResponseType type = 1 [default = DATA];
    /**
     * <code>required .ResponseType type = 1 [default = DATA];</code>
     */
    boolean hasType();
    /**
     * <code>required .ResponseType type = 1 [default = DATA];</code>
     */
    sniffer_prot.prot_buf.ResponseType getType();

    // optional bool interrupted = 2;
    /**
     * <code>optional bool interrupted = 2;</code>
     */
    boolean hasInterrupted();
    /**
     * <code>optional bool interrupted = 2;</code>
     */
    boolean getInterrupted();

    // repeated .SnifferResponse.RSSIRecord rssi_data = 3;
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    java.util.List<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord> 
        getRssiDataList();
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    sniffer_prot.prot_buf.SnifferResponse.RSSIRecord getRssiData(int index);
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    int getRssiDataCount();
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    java.util.List<? extends sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder> 
        getRssiDataOrBuilderList();
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder getRssiDataOrBuilder(
        int index);

    // optional .SnifferStatus status = 4;
    /**
     * <code>optional .SnifferStatus status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .SnifferStatus status = 4;</code>
     */
    sniffer_prot.prot_buf.SnifferStatus getStatus();
  }
  /**
   * Protobuf type {@code SnifferResponse}
   */
  public static final class SnifferResponse extends
      com.google.protobuf.GeneratedMessage
      implements SnifferResponseOrBuilder {
    // Use SnifferResponse.newBuilder() to construct.
    private SnifferResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SnifferResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SnifferResponse defaultInstance;
    public static SnifferResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SnifferResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SnifferResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sniffer_prot.prot_buf.ResponseType value = sniffer_prot.prot_buf.ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              interrupted_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                rssiData_ = new java.util.ArrayList<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord>();
                mutable_bitField0_ |= 0x00000004;
              }
              rssiData_.add(input.readMessage(sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              sniffer_prot.prot_buf.SnifferStatus value = sniffer_prot.prot_buf.SnifferStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          rssiData_ = java.util.Collections.unmodifiableList(rssiData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sniffer_prot.prot_buf.internal_static_SnifferResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sniffer_prot.prot_buf.internal_static_SnifferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sniffer_prot.prot_buf.SnifferResponse.class, sniffer_prot.prot_buf.SnifferResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SnifferResponse> PARSER =
        new com.google.protobuf.AbstractParser<SnifferResponse>() {
      public SnifferResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnifferResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SnifferResponse> getParserForType() {
      return PARSER;
    }

    public interface RSSIRecordOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional bytes mac = 1;
      /**
       * <code>optional bytes mac = 1;</code>
       */
      boolean hasMac();
      /**
       * <code>optional bytes mac = 1;</code>
       */
      com.google.protobuf.ByteString getMac();

      // optional int32 rssi = 2;
      /**
       * <code>optional int32 rssi = 2;</code>
       */
      boolean hasRssi();
      /**
       * <code>optional int32 rssi = 2;</code>
       */
      int getRssi();

      // optional int32 id = 3;
      /**
       * <code>optional int32 id = 3;</code>
       */
      boolean hasId();
      /**
       * <code>optional int32 id = 3;</code>
       */
      int getId();
    }
    /**
     * Protobuf type {@code SnifferResponse.RSSIRecord}
     */
    public static final class RSSIRecord extends
        com.google.protobuf.GeneratedMessage
        implements RSSIRecordOrBuilder {
      // Use RSSIRecord.newBuilder() to construct.
      private RSSIRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RSSIRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RSSIRecord defaultInstance;
      public static RSSIRecord getDefaultInstance() {
        return defaultInstance;
      }

      public RSSIRecord getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RSSIRecord(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                mac_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                rssi_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                id_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sniffer_prot.prot_buf.internal_static_SnifferResponse_RSSIRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sniffer_prot.prot_buf.internal_static_SnifferResponse_RSSIRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.class, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder.class);
      }

      public static com.google.protobuf.Parser<RSSIRecord> PARSER =
          new com.google.protobuf.AbstractParser<RSSIRecord>() {
        public RSSIRecord parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RSSIRecord(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RSSIRecord> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional bytes mac = 1;
      public static final int MAC_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString mac_;
      /**
       * <code>optional bytes mac = 1;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes mac = 1;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }

      // optional int32 rssi = 2;
      public static final int RSSI_FIELD_NUMBER = 2;
      private int rssi_;
      /**
       * <code>optional int32 rssi = 2;</code>
       */
      public boolean hasRssi() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 rssi = 2;</code>
       */
      public int getRssi() {
        return rssi_;
      }

      // optional int32 id = 3;
      public static final int ID_FIELD_NUMBER = 3;
      private int id_;
      /**
       * <code>optional int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }

      private void initFields() {
        mac_ = com.google.protobuf.ByteString.EMPTY;
        rssi_ = 0;
        id_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, mac_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, rssi_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, id_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, mac_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, rssi_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, id_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(sniffer_prot.prot_buf.SnifferResponse.RSSIRecord prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SnifferResponse.RSSIRecord}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return sniffer_prot.prot_buf.internal_static_SnifferResponse_RSSIRecord_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return sniffer_prot.prot_buf.internal_static_SnifferResponse_RSSIRecord_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.class, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder.class);
        }

        // Construct using sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          mac_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          rssi_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return sniffer_prot.prot_buf.internal_static_SnifferResponse_RSSIRecord_descriptor;
        }

        public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord getDefaultInstanceForType() {
          return sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.getDefaultInstance();
        }

        public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord build() {
          sniffer_prot.prot_buf.SnifferResponse.RSSIRecord result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord buildPartial() {
          sniffer_prot.prot_buf.SnifferResponse.RSSIRecord result = new sniffer_prot.prot_buf.SnifferResponse.RSSIRecord(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.mac_ = mac_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.rssi_ = rssi_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.id_ = id_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof sniffer_prot.prot_buf.SnifferResponse.RSSIRecord) {
            return mergeFrom((sniffer_prot.prot_buf.SnifferResponse.RSSIRecord)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(sniffer_prot.prot_buf.SnifferResponse.RSSIRecord other) {
          if (other == sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.getDefaultInstance()) return this;
          if (other.hasMac()) {
            setMac(other.getMac());
          }
          if (other.hasRssi()) {
            setRssi(other.getRssi());
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          sniffer_prot.prot_buf.SnifferResponse.RSSIRecord parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (sniffer_prot.prot_buf.SnifferResponse.RSSIRecord) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional bytes mac = 1;
        private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes mac = 1;</code>
         */
        public boolean hasMac() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional bytes mac = 1;</code>
         */
        public com.google.protobuf.ByteString getMac() {
          return mac_;
        }
        /**
         * <code>optional bytes mac = 1;</code>
         */
        public Builder setMac(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          mac_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes mac = 1;</code>
         */
        public Builder clearMac() {
          bitField0_ = (bitField0_ & ~0x00000001);
          mac_ = getDefaultInstance().getMac();
          onChanged();
          return this;
        }

        // optional int32 rssi = 2;
        private int rssi_ ;
        /**
         * <code>optional int32 rssi = 2;</code>
         */
        public boolean hasRssi() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 rssi = 2;</code>
         */
        public int getRssi() {
          return rssi_;
        }
        /**
         * <code>optional int32 rssi = 2;</code>
         */
        public Builder setRssi(int value) {
          bitField0_ |= 0x00000002;
          rssi_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 rssi = 2;</code>
         */
        public Builder clearRssi() {
          bitField0_ = (bitField0_ & ~0x00000002);
          rssi_ = 0;
          onChanged();
          return this;
        }

        // optional int32 id = 3;
        private int id_ ;
        /**
         * <code>optional int32 id = 3;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 id = 3;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>optional int32 id = 3;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000004;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 id = 3;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          id_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:SnifferResponse.RSSIRecord)
      }

      static {
        defaultInstance = new RSSIRecord(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:SnifferResponse.RSSIRecord)
    }

    private int bitField0_;
    // required .ResponseType type = 1 [default = DATA];
    public static final int TYPE_FIELD_NUMBER = 1;
    private sniffer_prot.prot_buf.ResponseType type_;
    /**
     * <code>required .ResponseType type = 1 [default = DATA];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ResponseType type = 1 [default = DATA];</code>
     */
    public sniffer_prot.prot_buf.ResponseType getType() {
      return type_;
    }

    // optional bool interrupted = 2;
    public static final int INTERRUPTED_FIELD_NUMBER = 2;
    private boolean interrupted_;
    /**
     * <code>optional bool interrupted = 2;</code>
     */
    public boolean hasInterrupted() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool interrupted = 2;</code>
     */
    public boolean getInterrupted() {
      return interrupted_;
    }

    // repeated .SnifferResponse.RSSIRecord rssi_data = 3;
    public static final int RSSI_DATA_FIELD_NUMBER = 3;
    private java.util.List<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord> rssiData_;
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    public java.util.List<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord> getRssiDataList() {
      return rssiData_;
    }
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    public java.util.List<? extends sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder> 
        getRssiDataOrBuilderList() {
      return rssiData_;
    }
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    public int getRssiDataCount() {
      return rssiData_.size();
    }
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord getRssiData(int index) {
      return rssiData_.get(index);
    }
    /**
     * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
     */
    public sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder getRssiDataOrBuilder(
        int index) {
      return rssiData_.get(index);
    }

    // optional .SnifferStatus status = 4;
    public static final int STATUS_FIELD_NUMBER = 4;
    private sniffer_prot.prot_buf.SnifferStatus status_;
    /**
     * <code>optional .SnifferStatus status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .SnifferStatus status = 4;</code>
     */
    public sniffer_prot.prot_buf.SnifferStatus getStatus() {
      return status_;
    }

    private void initFields() {
      type_ = sniffer_prot.prot_buf.ResponseType.DATA;
      interrupted_ = false;
      rssiData_ = java.util.Collections.emptyList();
      status_ = sniffer_prot.prot_buf.SnifferStatus.SNIFFING_STOPED;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, interrupted_);
      }
      for (int i = 0; i < rssiData_.size(); i++) {
        output.writeMessage(3, rssiData_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, interrupted_);
      }
      for (int i = 0; i < rssiData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, rssiData_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sniffer_prot.prot_buf.SnifferResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sniffer_prot.prot_buf.SnifferResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SnifferResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sniffer_prot.prot_buf.SnifferResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sniffer_prot.prot_buf.internal_static_SnifferResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sniffer_prot.prot_buf.internal_static_SnifferResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sniffer_prot.prot_buf.SnifferResponse.class, sniffer_prot.prot_buf.SnifferResponse.Builder.class);
      }

      // Construct using sniffer_prot.prot_buf.SnifferResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRssiDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = sniffer_prot.prot_buf.ResponseType.DATA;
        bitField0_ = (bitField0_ & ~0x00000001);
        interrupted_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (rssiDataBuilder_ == null) {
          rssiData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          rssiDataBuilder_.clear();
        }
        status_ = sniffer_prot.prot_buf.SnifferStatus.SNIFFING_STOPED;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sniffer_prot.prot_buf.internal_static_SnifferResponse_descriptor;
      }

      public sniffer_prot.prot_buf.SnifferResponse getDefaultInstanceForType() {
        return sniffer_prot.prot_buf.SnifferResponse.getDefaultInstance();
      }

      public sniffer_prot.prot_buf.SnifferResponse build() {
        sniffer_prot.prot_buf.SnifferResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sniffer_prot.prot_buf.SnifferResponse buildPartial() {
        sniffer_prot.prot_buf.SnifferResponse result = new sniffer_prot.prot_buf.SnifferResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.interrupted_ = interrupted_;
        if (rssiDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            rssiData_ = java.util.Collections.unmodifiableList(rssiData_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.rssiData_ = rssiData_;
        } else {
          result.rssiData_ = rssiDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sniffer_prot.prot_buf.SnifferResponse) {
          return mergeFrom((sniffer_prot.prot_buf.SnifferResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sniffer_prot.prot_buf.SnifferResponse other) {
        if (other == sniffer_prot.prot_buf.SnifferResponse.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasInterrupted()) {
          setInterrupted(other.getInterrupted());
        }
        if (rssiDataBuilder_ == null) {
          if (!other.rssiData_.isEmpty()) {
            if (rssiData_.isEmpty()) {
              rssiData_ = other.rssiData_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRssiDataIsMutable();
              rssiData_.addAll(other.rssiData_);
            }
            onChanged();
          }
        } else {
          if (!other.rssiData_.isEmpty()) {
            if (rssiDataBuilder_.isEmpty()) {
              rssiDataBuilder_.dispose();
              rssiDataBuilder_ = null;
              rssiData_ = other.rssiData_;
              bitField0_ = (bitField0_ & ~0x00000004);
              rssiDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRssiDataFieldBuilder() : null;
            } else {
              rssiDataBuilder_.addAllMessages(other.rssiData_);
            }
          }
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sniffer_prot.prot_buf.SnifferResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sniffer_prot.prot_buf.SnifferResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .ResponseType type = 1 [default = DATA];
      private sniffer_prot.prot_buf.ResponseType type_ = sniffer_prot.prot_buf.ResponseType.DATA;
      /**
       * <code>required .ResponseType type = 1 [default = DATA];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ResponseType type = 1 [default = DATA];</code>
       */
      public sniffer_prot.prot_buf.ResponseType getType() {
        return type_;
      }
      /**
       * <code>required .ResponseType type = 1 [default = DATA];</code>
       */
      public Builder setType(sniffer_prot.prot_buf.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ResponseType type = 1 [default = DATA];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = sniffer_prot.prot_buf.ResponseType.DATA;
        onChanged();
        return this;
      }

      // optional bool interrupted = 2;
      private boolean interrupted_ ;
      /**
       * <code>optional bool interrupted = 2;</code>
       */
      public boolean hasInterrupted() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool interrupted = 2;</code>
       */
      public boolean getInterrupted() {
        return interrupted_;
      }
      /**
       * <code>optional bool interrupted = 2;</code>
       */
      public Builder setInterrupted(boolean value) {
        bitField0_ |= 0x00000002;
        interrupted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool interrupted = 2;</code>
       */
      public Builder clearInterrupted() {
        bitField0_ = (bitField0_ & ~0x00000002);
        interrupted_ = false;
        onChanged();
        return this;
      }

      // repeated .SnifferResponse.RSSIRecord rssi_data = 3;
      private java.util.List<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord> rssiData_ =
        java.util.Collections.emptyList();
      private void ensureRssiDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          rssiData_ = new java.util.ArrayList<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord>(rssiData_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          sniffer_prot.prot_buf.SnifferResponse.RSSIRecord, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder, sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder> rssiDataBuilder_;

      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public java.util.List<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord> getRssiDataList() {
        if (rssiDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rssiData_);
        } else {
          return rssiDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public int getRssiDataCount() {
        if (rssiDataBuilder_ == null) {
          return rssiData_.size();
        } else {
          return rssiDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord getRssiData(int index) {
        if (rssiDataBuilder_ == null) {
          return rssiData_.get(index);
        } else {
          return rssiDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder setRssiData(
          int index, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord value) {
        if (rssiDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRssiDataIsMutable();
          rssiData_.set(index, value);
          onChanged();
        } else {
          rssiDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder setRssiData(
          int index, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder builderForValue) {
        if (rssiDataBuilder_ == null) {
          ensureRssiDataIsMutable();
          rssiData_.set(index, builderForValue.build());
          onChanged();
        } else {
          rssiDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder addRssiData(sniffer_prot.prot_buf.SnifferResponse.RSSIRecord value) {
        if (rssiDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRssiDataIsMutable();
          rssiData_.add(value);
          onChanged();
        } else {
          rssiDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder addRssiData(
          int index, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord value) {
        if (rssiDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRssiDataIsMutable();
          rssiData_.add(index, value);
          onChanged();
        } else {
          rssiDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder addRssiData(
          sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder builderForValue) {
        if (rssiDataBuilder_ == null) {
          ensureRssiDataIsMutable();
          rssiData_.add(builderForValue.build());
          onChanged();
        } else {
          rssiDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder addRssiData(
          int index, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder builderForValue) {
        if (rssiDataBuilder_ == null) {
          ensureRssiDataIsMutable();
          rssiData_.add(index, builderForValue.build());
          onChanged();
        } else {
          rssiDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder addAllRssiData(
          java.lang.Iterable<? extends sniffer_prot.prot_buf.SnifferResponse.RSSIRecord> values) {
        if (rssiDataBuilder_ == null) {
          ensureRssiDataIsMutable();
          super.addAll(values, rssiData_);
          onChanged();
        } else {
          rssiDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder clearRssiData() {
        if (rssiDataBuilder_ == null) {
          rssiData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          rssiDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public Builder removeRssiData(int index) {
        if (rssiDataBuilder_ == null) {
          ensureRssiDataIsMutable();
          rssiData_.remove(index);
          onChanged();
        } else {
          rssiDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder getRssiDataBuilder(
          int index) {
        return getRssiDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder getRssiDataOrBuilder(
          int index) {
        if (rssiDataBuilder_ == null) {
          return rssiData_.get(index);  } else {
          return rssiDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public java.util.List<? extends sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder> 
           getRssiDataOrBuilderList() {
        if (rssiDataBuilder_ != null) {
          return rssiDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rssiData_);
        }
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder addRssiDataBuilder() {
        return getRssiDataFieldBuilder().addBuilder(
            sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder addRssiDataBuilder(
          int index) {
        return getRssiDataFieldBuilder().addBuilder(
            index, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .SnifferResponse.RSSIRecord rssi_data = 3;</code>
       */
      public java.util.List<sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder> 
           getRssiDataBuilderList() {
        return getRssiDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sniffer_prot.prot_buf.SnifferResponse.RSSIRecord, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder, sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder> 
          getRssiDataFieldBuilder() {
        if (rssiDataBuilder_ == null) {
          rssiDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sniffer_prot.prot_buf.SnifferResponse.RSSIRecord, sniffer_prot.prot_buf.SnifferResponse.RSSIRecord.Builder, sniffer_prot.prot_buf.SnifferResponse.RSSIRecordOrBuilder>(
                  rssiData_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          rssiData_ = null;
        }
        return rssiDataBuilder_;
      }

      // optional .SnifferStatus status = 4;
      private sniffer_prot.prot_buf.SnifferStatus status_ = sniffer_prot.prot_buf.SnifferStatus.SNIFFING_STOPED;
      /**
       * <code>optional .SnifferStatus status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .SnifferStatus status = 4;</code>
       */
      public sniffer_prot.prot_buf.SnifferStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .SnifferStatus status = 4;</code>
       */
      public Builder setStatus(sniffer_prot.prot_buf.SnifferStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SnifferStatus status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = sniffer_prot.prot_buf.SnifferStatus.SNIFFING_STOPED;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SnifferResponse)
    }

    static {
      defaultInstance = new SnifferResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SnifferResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SnifferQuery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SnifferQuery_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SnifferResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SnifferResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SnifferResponse_RSSIRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SnifferResponse_RSSIRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsniffer.proto\"I\n\014SnifferQuery\022&\n\004type\030" +
      "\001 \002(\0162\n.QueryType:\014DATA_REQUEST\022\021\n\trecor" +
      "d_id\030\002 \001(\005\"\316\001\n\017SnifferResponse\022!\n\004type\030\001" +
      " \002(\0162\r.ResponseType:\004DATA\022\023\n\013interrupted" +
      "\030\002 \001(\010\022.\n\trssi_data\030\003 \003(\0132\033.SnifferRespo" +
      "nse.RSSIRecord\022\036\n\006status\030\004 \001(\0162\016.Sniffer" +
      "Status\0323\n\nRSSIRecord\022\013\n\003mac\030\001 \001(\014\022\014\n\004rss" +
      "i\030\002 \001(\005\022\n\n\002id\030\003 \001(\005*1\n\tQueryType\022\022\n\016STAT" +
      "US_REQUEST\020\000\022\020\n\014DATA_REQUEST\020\001*$\n\014Respon" +
      "seType\022\010\n\004DATA\020\000\022\n\n\006STATUS\020\001*6\n\rSnifferS",
      "tatus\022\023\n\017SNIFFING_STOPED\020\000\022\020\n\014SNIFFING_R" +
      "UN\020\001B\030\n\014sniffer_protB\010prot_buf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SnifferQuery_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SnifferQuery_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SnifferQuery_descriptor,
              new java.lang.String[] { "Type", "RecordId", });
          internal_static_SnifferResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SnifferResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SnifferResponse_descriptor,
              new java.lang.String[] { "Type", "Interrupted", "RssiData", "Status", });
          internal_static_SnifferResponse_RSSIRecord_descriptor =
            internal_static_SnifferResponse_descriptor.getNestedTypes().get(0);
          internal_static_SnifferResponse_RSSIRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SnifferResponse_RSSIRecord_descriptor,
              new java.lang.String[] { "Mac", "Rssi", "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
